# GitHub Pages config

title: Mastodon TypeScript Library
description: Version 0.0.6
author: © TypeScriptLibs
email: bug@typescriptlibs.org
github_username:  typescriptlibs
rss: rss

show_excerpts: false

github:
  private: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-titles-from-headings

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: auto

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
